#### Static Provisioning #### 
---
apiVersion: v1
kind: Namespace
metadata: 
  name: demo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain    ### If set as "Delete" option will be selected then container would be removed after pvc deletion.
  storageClassName: azureblob-fuse-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: nokoyaza
    volumeAttributes:
      resourceGroup: aks-rg
      storageAccount: aks24bd32be
      containerName: nokoyaza-project
      secretName: azure-secret
      protocol: fuse
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob
  namespace: demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob
  storageClassName: azureblob-fuse-premium
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nokoyaza-deployment
  namespace: demo
spec:
  selector: 
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mypod
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myvol
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: myvol
        persistentVolumeClaim:
          claimName: pvc-blob

